#!/bin/bash


print_volume() {
	volume="$(pamixer --get-volume-human)"
	echo -e "V:$volume"
	#volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
        #if test "$volume" -gt 0
        #then
        #	echo -e "\uE05D${volume}"
        #else
        #	echo -e "Mute"
        #fi
}

print_load(){
	echo "$(cat /proc/loadavg | cut -d' ' --fields=1,2,3)"
	#echo "Load:$(cat /proc/loadavg)"
}

print_mem(){
        memfree=$(($(grep -m1 'MemAvailable:' /proc/meminfo | awk '{print $2}') / 1024 ))
        echo -e "$memfree Mb"
        #echo -e "Free:$memfree Mb"
}

print_date(){
        date "+%a %d-%m %T"
}

print_temp(){
	if grep -q 'BigPapa' /etc/hostname; then
		echo "$(sensors -u | awk '/Tdie/{getline; print $2}' | head -c 2)C"
	else
		test -f /sys/class/thermal/thermal_zone0/temp || return 0
		echo "$(head -c 2 /sys/class/thermal/thermal_zone0/temp)C"
	fi
}

print_power() {
        if hash acpi 2>/dev/null
        then
		echo -e "|$(acpi | sed '/unavailable/d' | sed 's/Battery.[0-9]:.//g')"
        else
		echo -e ""
        fi
}

print_ip() {
	echo "$(nmcli | grep inet4 | sed '/127.0.0.1/d' | cut -d' ' -f 2)"	
}

print_music() {
	if  mpc 2>/dev/null | grep -q playing; then
		echo "|$(mpc current)"	
	fi
	if  playerctl status -p spotify 2>/dev/null| grep -q Playing; then
		echo "|$(playerctl -p spotify metadata --format '{{artist}} - {{title}}')"
	fi
}

while true
do


	xsetroot -name "$(print_music)|$(print_ip)|$(print_load)|$(print_mem)|$(print_temp)|$(print_volume)$(print_power)|$(print_date)"

        sleep 2

done

