#!/bin/sh
xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --mode 1680x1050 --pos 0x0 --rotate left --output HDMI-0 --primary --mode 2560x1440 --pos 1050x120 --rotate normal --output DP-4 --off --output DP-5 --off
xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --mode 1680x1050 --pos 0x0 --rotate right --output HDMI-0 --primary --mode 2560x1440 --pos 1050x0 --rotate normal --output DP-4 --off --output DP-5 --off

feh --randomize --bg-tile ~/.config/wallpapers/*
#feh --bg-tile ~/.config/wallpapers/background.jpg

xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --mode 1680x1050 --pos 0x0 --rotate right --output HDMI-0 --primary --mode 2560x1440 --pos 1050x0 --rotate normal --output DP-4 --off --output DP-5 --off
