#!/bin/sh
$BROWSER -new-tab https://timetable.necaeducation.com.au:44304 -new-tab https://online.vitalsource.com/home/my-library -new-tab file:///home/papa/Nextcloud/Electrical/AS3000-2023.pdf -new-tab https://sparky.necaeducation.com.au/my/
