#!/bin/sh
$BROWSER -new-tab https://earth.nullschool.net/#current/wind/surface/level/orthographic=-220.57,-36.32,3277 -new-tab https://www.willyweather.com.au/maps.html?style=ww\&provider=id:2,offset:-60\&id=13794\&lat=-37.7808\&lng=144.9355 -new-tab https://www.willyweather.com.au/vic/melbourne/travancore.html
