#!/bin/sh
xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --mode 1680x1050 --pos 2560x0 --rotate left --output HDMI-0 --primary --mode 2560x1440 --pos 0x120 --rotate normal --output DP-4 --off --output DP-5 --off

feh --bg-tile /home/papa/dotfiles/common/background.jpg
