-- Generated by nwg-displays on 2026-09-26 at 16:17:53. Do not edit manually.

hl.monitor({
    output = "desc:ViewSonic Corporation VX3276-QHD V9W194341415",
    mode = "2560x1440@59.95",
    position = "1050x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "desc:Dell Inc. DELL E228WFP WM4976B801TM",
    mode = "1680x1050@59.88",
    position = "0x0",
    scale = 1,
    vrr = 0,
    transform = 1
})
